### ISSUE TITLE
请问如何使用呢？

### ISSUE THREAD

**Issue by AlexLove77** [dowenliu-xyz/elasticsearch-analysis-char-filter-chinese-simplifying#1]
您好，请问这个插件如何使用？

我现在想添加这个 char filter 到ik分词器，在分词之前先把全部词语转成 简体或者繁体，然后做index; 相应的，在搜索的时候，也都把输入转到同一语言然后再搜索，确保繁体内容我输入简体字也可以搜到相应结果。
尝试mvn package，Could not resolve lucene-char-filter-chinese-simplifying:jar:5.5.0.0 .

谢谢！

---

已經配置安裝成功，謝謝

**Comment by dowenliu-xyz** [comment]
先检出项目[lucene-char-filter-chinese-simplifying](https://github.com/dowenliu-xyz/lucene-char-filter-chinese-simplifying)，git checkout到tag 5.5.0.0，mvn install到本地仓

之后再切回本项目执行mvn package就能打包了

安装的话：_ES_HOME_/bin/plugin install file:/_path/to/project_/target/releases/elasticsearch-analysis-char-filter-chinese-simplifying-2.3._x.y_-dist.zip

配置的话你自己查下官网文档。_char_filter_ 名为_chinese-simplifying_

**Comment by AlexLove77** [comment]
安裝配置成功，謝謝！
